# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pub_date',
        ),
    ]
