# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
