# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(default='http'),
        ),
    ]
