# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180121_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(),
        ),
    ]
