# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180121_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer_id',
            field=models.IntegerField(default=0),
        ),
    ]
